export const patients_inputs = (id, cedula, nombre, nombre_emer, apellido_1, apellido_2, email, pass, fecha_nacimiento, direccion, telefono, telefono_emer, genero_id, estado, tipo_id,tipo_sangre,allergies, enfermedades) => {
    return [
        {
            id: id || "",
            label: "Cedula",
            name: "cedula",
            value: cedula || "",
            onChange: null,
            autoFocus: true,
            submitted: null,
            type: "int",
            keyfilter: "int",
        },
        {
            id: "",
            label: "Nombre",
            name: "nombre",
            value: nombre || "",
            onChange: null,
            autoFocus: false,
            submitted: null,
            type: "text",
            keyfilter: 'alpha'
        },
        {
            id: "",
            label: "Nombre de emergencia",
            name: "nombre_emer",
            value: nombre_emer || "",
            onChange: null,
            autoFocus: false,
            submitted: null,
            type: "text",
            keyfilter: 'alpha'
        },
        {
            id: "",
            label: "Primer apellido",
            name: "apellido_1",
            value: apellido_1 || "",
            onChange: null,
            autoFocus: false,
            submitted: null,
            type: "text",
            keyfilter: 'alpha'
        },
        {
            id: "",
            label: "Segundo apellido",
            name: "apellido_2",
            value: apellido_2 || "",
            onChange: null,
            autoFocus: false,
            submitted: null,
            type: "text",
            keyfilter: 'alpha'
        },
        {
            id: "",
            label: "Email",
            name: "email",
            value: email || "",
            onChange: null,
            autoFocus: false,
            submitted: null,
            type: "text",
        },
        {
            id: "",
            label: "Contraseña",
            name: "pass",
            value: pass || "",
            onChange: null,
            autoFocus: false,
            submitted: null,
            type: "pass",
        },
        {
            id: "",
            label: "Fecha de nacimiento",
            name: "fecha_nacimiento",
            value: fecha_nacimiento || "",
            onChange: null,
            autoFocus: false,
            submitted: null,
            type: "date",

        },
        {
            id: "",
            label: "Dirección",
            name: "direccion",
            value: direccion || "",
            onChange: null,
            autoFocus: false,
            submitted: null,
            type: "text",
        },
        {
            id: "",
            label: "Teléfono",
            name: "telefono",
            value: telefono || "",
            onChange: null,
            autoFocus: false,
            submitted: null,
            type: "int",
            keyfilter: "int",
        },
        {
            id: "telefono_emer",
            label: "Teléfono de emergencia",
            name: "telefono_emer",
            value: telefono_emer || "",
            onChange: null,
            autoFocus: false,
            submitted: null,
            type: "int",
            keyfilter: "int",
        },
        {
            id: "genero_id",
            label: "Género",
            name: "genero_id",
            value: genero_id || 0,
            onChange: null,
            autoFocus: false,
            submitted: null,
            type: "select",
        },
        {
            id: "tipo_id",
            label: "Tipo de Usuario",
            name: "tipo_id",
            value: tipo_id || 0,
            onChange: null,
            autoFocus: false,
            submitted: null,
            type: "select",
        },
        {
            id: "estado",
            label: "Estado",
            name: "estado",
            value: estado || 0,
            onChange: null,
            autoFocus: false,
            submitted: null,
            type: "checkbox",
        },
        {
            id: "",
            label: "Tipo de Sangre",
            name: "tipo_sangre",
            value: tipo_sangre || 0,
            onChange: null,
            autoFocus: false,
            submitted: null,
            type: "select"
        },
        {
            id: "",
            label: "Alergias",
            name: "allergies",
            value: allergies || [],
            onChange: null,
            autoFocus: false,
            submitted: null,
            type: "listBox"
        },
        {
            id: "",
            label: "Enfermedades",
            name: "enfermedades",
            value: enfermedades || [],
            onChange: null,
            autoFocus: false,
            submitted: null,
            type: "listBox"
        }
    ];
}

